project 'spark.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod "ChameleonFramework"
  pod "Alamofire"
  pod 'JTAppleCalendar'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'	
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

  # Pods for spark

  target 'sparkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sparkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
